### ISSUE TITLE
error: qAlgorithm exits when no profile data is supplied

### ISSUE THREAD

**Issue by LeonSaal** [odea-project/qAlgorithms#11]
Hi there,

I'm having an issue, when I try to process already centroided (with msconvert) data. 
After successfully reading in the file the program exits after announcing the peak processing:

```powershell
> qAlgorithms_013beta.exe -i "D:\ ... .mzML" -o "." -pp
Warning: the processing log has been overwritten
printing output to: "."
reading file 1 of 1:
"D:\ ... .mzML"
...  file ok
Warning: qAlgorithms is intended for profile spectra. A base uncertainty of 5 ppm is assumed for all supplied centroids
Processing positive peaks
> 
```
What is the problem here?

Kind regards,

Leon

**Comment by dahoehn** [comment]
Hello Leon, 
I was not able to reproduce your error (using the 0.1.3 beta release) when centroiding a test file with MSconvert myself. Could you post the settings used for conversion and the mass analyser used? I only tried orbitrap files (.raw) for the time being.
I do, however, expect it to be an error in the program due to the ppm warning not triggering for me.

Also note that i am reworking the program and identified a calculation error which has since been fixed. Any results you have generated so far are at least slightly inaccurate. I fixed it now, but the next release will still take around one week. I suggest you try again with the new build once it's ready.

**Comment by LeonSaal** [comment]
Hi Daniel,

thanks for looking into my problem and the heads-up on the calculation error!

I'm using an Agilent TOF mass analyzer (6545 QTOF) and the _msconvert_ settings are as follows: `"msconvert.exe" --zlib --filter "peakPicking vendor msLevel=1-" --filter "titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File:"""^<SourcePath^>""", NativeID:"""^<Id^>""""  `

Kind regards,

Leon

**Comment by dahoehn** [comment]
Hi Leon,
The msconvert options are the same i used, so it should be fine. Does the program correctly process non-centroided QTOF data? 
Since we don't have an agilent TOF, i won't be able to find a bug without at least one file to test, assuming it persists.

Greetings,
Daniel

**Comment by dahoehn** [comment]
Hello Leon,
I have published the new release. Let me know if it does or doesn't work.
I have tested it on 12 precentroided files of a SFC-ToF measurement series, all of which produced a feature list without issue. Note that it is significantly slower than the previous version, since i removed multithreading until correctness tests are integrated into the program. 

Greetings,
Daniel

**Comment by LeonSaal** [comment]
Hi Daniel,

thanks for the notification and the addendum, I will look into that! For now, I can say, that it works with the already centroided datafile.

Kind regards,

Leon

**Comment by LeonSaal** [comment]
A follow-up on the estimation of ppm:
As qBinning uses the mzUncertainty-value from qCentroids, why can't I just use some summarizing statistic of the mzUncertainty-column from profile data?

**Comment by dahoehn** [comment]
I've thought about doing that myself, but haven't discovered a way to express the centroid error with any reasonable certainty as a property relating to centroid properties, or any other sum parameter for that matter. The peak shape gets lost after forming the centroid, and recontructing it is also not possible as a general. If you have both profile and centroid mode files, you could centroid it with qAlgorithms and correlate the error with the feature list otherwise obtained, but i don't have the time to write a program for that at the moment.

**Comment by dahoehn** [comment]
I have added a wiki page which contains the relevant details of this issue.
