### ISSUE TITLE
error: Assertion failed

### ISSUE THREAD

**Issue by LeonSaal** [odea-project/qAlgorithms#13]
Hi Daniel,

during processing with 0.2.1 beta I got the following error:
```powershell
> ..\qAlgorithms_021beta -i "... .mzML" -o "." -pf -v

reading file 1 of 1:
"D:\\... .mzML"
...  file ok
Assertion failed: coeff[0] != 0, file C:/Users/unisys/Documents/Studium/Analytik-Praktikum/qAlgorithms/src/qalgorithms_qpeaks.cpp, line 1469
```

Profile data was created with msconvert
```
"msconvert.exe" --zlib --filter "msLevel 1-1" --filter "titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File:"""^<SourcePath^>""", NativeID:"""^<Id^>""""  
```
for 3 of 4 files, measured with the same method this happened.

Kind regards,

Leon

**Comment by dahoehn** [comment]
Hi Leon, 
thanks for the information. We are fairly certain that this condition does not invalidate the correctness of our program, and will take the check out. Should you see nonsense results, or otherwise strange patterns, please let us know.
I have uploaded a patched release of 0.2.1.
Greetings,
Daniel
